package chapter49;


/**
* chapter49/GoodDay.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chapter49.idl
* martes 4 de octubre de 2016 13h'05 ART
*/

public interface GoodDay extends GoodDayOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GoodDay
