package chapter49;


/**
* chapter49/GoodDayHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chapter49.idl
* martes 4 de octubre de 2016 13h'05 ART
*/

abstract public class GoodDayHelper
{
  private static String  _id = "IDL:chapter49/GoodDay:1.0";

  public static void insert (org.omg.CORBA.Any a, chapter49.GoodDay that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static chapter49.GoodDay extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (chapter49.GoodDayHelper.id (), "GoodDay");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static chapter49.GoodDay read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GoodDayStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, chapter49.GoodDay value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static chapter49.GoodDay narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof chapter49.GoodDay)
      return (chapter49.GoodDay)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      chapter49._GoodDayStub stub = new chapter49._GoodDayStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static chapter49.GoodDay unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof chapter49.GoodDay)
      return (chapter49.GoodDay)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      chapter49._GoodDayStub stub = new chapter49._GoodDayStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
