package chapter49;


/**
* chapter49/GoodDayOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chapter49.idl
* martes 4 de octubre de 2016 13h'05 ART
*/

public interface GoodDayOperations 
{
  String hello (org.omg.CORBA.ShortHolder hour, org.omg.CORBA.ShortHolder minute);
} // interface GoodDayOperations
