package chapter49;

/**
* chapter49/GoodDayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chapter49.idl
* martes 4 de octubre de 2016 13h'05 ART
*/

public final class GoodDayHolder implements org.omg.CORBA.portable.Streamable
{
  public chapter49.GoodDay value = null;

  public GoodDayHolder ()
  {
  }

  public GoodDayHolder (chapter49.GoodDay initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chapter49.GoodDayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chapter49.GoodDayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chapter49.GoodDayHelper.type ();
  }

}
