package chapter49;


/**
* chapter49/GoodDayPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chapter49.idl
* martes 4 de octubre de 2016 13h'05 ART
*/

public abstract class GoodDayPOA extends org.omg.PortableServer.Servant
 implements chapter49.GoodDayOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("hello", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // chapter49/GoodDay/hello
       {
         org.omg.CORBA.ShortHolder hour = new org.omg.CORBA.ShortHolder ();
         org.omg.CORBA.ShortHolder minute = new org.omg.CORBA.ShortHolder ();
         String $result = null;
         $result = this.hello (hour, minute);
         out = $rh.createReply();
         out.write_string ($result);
         out.write_short (hour.value);
         out.write_short (minute.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:chapter49/GoodDay:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GoodDay _this() 
  {
    return GoodDayHelper.narrow(
    super._this_object());
  }

  public GoodDay _this(org.omg.CORBA.ORB orb) 
  {
    return GoodDayHelper.narrow(
    super._this_object(orb));
  }


} // class GoodDayPOA
